In [1]:
from transformers import pipeline

In [2]:
!pip install transformers

In [3]:
chatbot=pipeline(task="conversational",model="facebook/blenderbot-400M-distill")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/1.57k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/730M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/127k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/62.9k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/16.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/310k [00:00<?, ?B/s]

In [4]:
user_message="""
What is food?
"""

In [5]:
from transformers import Conversation

In [6]:
conversation=Conversation(user_message)

In [7]:

print(conversation)

Conversation id: 7a0b9131-e303-40a2-bf8d-a1308d91ae29
user: 
What is food?




In [8]:
conversation=chatbot(conversation)

No chat template is set for this tokenizer, falling back to a default class-level template. This is very error-prone, because models are often trained with templates different from the class default! Default chat templates are a legacy feature and will be removed in Transformers v4.43, at which point any code depending on them will stop working. We recommend setting a valid chat template before then to ensure that this model continues working without issues.


In [9]:
print(conversation)

Conversation id: 7a0b9131-e303-40a2-bf8d-a1308d91ae29
user: 
What is food?

assistant:  Food is food that is prepared for consumption with or without the use of heat.



In [11]:
print(chatbot(Conversation("What else do u recommend?")))

Conversation id: 6fc824a1-b329-42e7-b3c6-fad41f321d40
user: What else do u recommend?
assistant:  Well, I'm not sure what else I can think of, but I do know that I can't wait to go back to school.



In [12]:
#memory


conversation.add_message({"role":"user","content":"""what else do u recommend?"""})

In [13]:
print(conversation)

Conversation id: 7a0b9131-e303-40a2-bf8d-a1308d91ae29
user: 
What is food?

assistant:  Food is food that is prepared for consumption with or without the use of heat.
user: what else do u recommend?



In [14]:
#NLP is field of field of ml and linguistics.
#common NLP tasks:
# text generation, sentence similarity, summarization, machine translation.


In [15]:
print(chatbot(Conversation("What else do you recommend?")))

Conversation id: f577e968-4ca3-452d-99f1-bd82bd640e8c
user: What else do you recommend?
assistant:  Well, I'm not sure what else I can think of, but I do know that I'm going to miss her.



In [17]:
print(chatbot(Conversation(input())))

what are your 4 names?
Conversation id: 5afae641-6561-4512-8206-8a48a192029d
user: what are your 4 names?
assistant:  I don't have any names yet. I'm still trying to figure out what to name them.



In [ ]:
while True:
  print(chatbot(Conversation(input())))

Conversation id: 05b751f0-bd28-49e8-a989-c68ad30afcca
user: who are you?
assistant:  I don't want to say.  I just want to get it out of my head.

Conversation id: 888b31e5-753f-4cc0-8347-70c65e59498f
user: dude do u have emotions?
assistant:  Yes, I do.  I have a lot of them.  Do you have any?

Conversation id: bec77bfd-70f5-46ed-a3c8-301083ecb0f0
user: no
assistant:  Do you have any pets? I have a dog and a cat. I love them so much.

Conversation id: e8190872-adce-426f-a76a-b503f10f8000
user: tell me your name
assistant:  My name is Jessica. How about you? What do you do for a living?

Conversation id: b1f2ffc4-fd16-4f92-a3ff-b51b24ff8601
user: give me your instagram id
assistant:  I don't have an instagram, but I do have a facebook account. Do you have one?

Conversation id: b1e57e46-9f74-413c-b809-596c15ce5d68
user: give me your facebook id
assistant:  I don't have a facebook, but I do have instagram. Do you have one?



**Translation and summarization**


*   Language Translation
*   Text Summarization



In [18]:
pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

In [21]:
import torch

In [22]:
translator=pipeline(task="translation",model="facebook/nllb-200-distilled-600M", torch_dtype=torch.bfloat16)

pytorch_model.bin:  72%|#######2  | 1.77G/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/3.55k [00:00<?, ?B/s]

In [27]:
text = """\
My puppy is adorable,\
your kitten is cute.
her panda is friendly.
His llama is thoughtful, \
we all have nice pets !"""


In [28]:
text_translated=translator((text),src_lang="eng_Latn",
                                 tgt_lang="fra_Latn")

In [30]:
print(text_translated)

[{'translation_text': 'Mon chiot est adorable, ton chaton est mignon, son panda est amicale, son lama est attentionné, nous avons tous de beaux animaux de compagnie !'}]


In [31]:
import gc


In [33]:
del translator

In [34]:
gc.collect()

1170

In [35]:
summarizer=pipeline(task="summarization",model="facebook/bart-large-cnn",torch_dtype=torch.bfloat16)

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [36]:
text="The City of Paris is the centre of the Île-de-France region, or Paris Region, with an official estimated population of 12,271,794 inhabitants on 1 January 2023, or about 19% of the population of France.[2] The Paris Region had a GDP of €765 billion (US$1.064 trillion, PPP)[8] in 2021, the highest in the European Union.[9] According to the Economist Intelligence Unit Worldwide Cost of Living Survey, in 2022, Paris was the city with the ninth-highest cost of living in the world"

In [37]:
summary=summarizer(text,max_length=100,min_length=10)

In [38]:
print(summary)

[{'summary_text': 'The City of Paris is the centre of the Île-de-France region, or Paris Region. The Paris Region had a GDP of €765 billion (US$1.064 trillion, PPP)[8] in 2021, the highest in the European Union. Paris was the city with the ninth-highest cost of living in the world in 2022.'}]


#  Sentence Embeddings

In [39]:
pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.7/224.7 kB 4.5 MB/s eta 0:00:00


In [43]:
import sentence_transformers
from sentence_transformers import SentenceTransformer

In [44]:
model=SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [45]:
sentences1=['The cat sits outside',
            'A man is playing guitar',
            'The movies are awesome']

In [47]:
embeddings1=model.encode(sentences1,convert_to_tensor=True)

In [48]:
embeddings1

tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]])

In [49]:
sentences2=['The dog plays in the garden',
            'A woman watches TV',
            ' The new movie is so great']

In [50]:
embeddings2=model.encode(sentences2,convert_to_tensor=True)

In [51]:
embeddings2

tensor([[ 0.0163, -0.0700,  0.0384,  ...,  0.0447,  0.0254, -0.0023],
        [ 0.0054, -0.0920,  0.0140,  ...,  0.0167, -0.0086, -0.0424],
        [-0.0842, -0.0592, -0.0010,  ..., -0.0157,  0.0764,  0.0389]])

In [52]:
from sentence_transformers import util

In [62]:
cosine_scores=util.cos_sim(embeddings1,embeddings2)

In [63]:
print(cosine_scores)

tensor([[ 0.2838,  0.1310, -0.0029],
        [ 0.2277, -0.0327, -0.0136],
        [-0.0124, -0.0465,  0.6571]])


In [66]:
for x in range(len(cosine_scores)):
  for y in range(len(cosine_scores)):
    a=float(cosine_scores[x][y])
print(a)


0.6571146845817566


In [71]:
cosine_scores.float()


tensor([[ 0.2838,  0.1310, -0.0029],
        [ 0.2277, -0.0327, -0.0136],
        [-0.0124, -0.0465,  0.6571]])

In [73]:
print(cosine_scores)

tensor([[ 0.2838,  0.1310, -0.0029],
        [ 0.2277, -0.0327, -0.0136],
        [-0.0124, -0.0465,  0.6571]])


#cosine_score is a similarity index

In [74]:
for i in range(len(sentences1)):
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i],
                                                 sentences2[i],
                                                 cosine_scores[i][i]))

The cat sits outside 		 The dog plays in the garden 		 Score: 0.2838
A man is playing guitar 		 A woman watches TV 		 Score: -0.0327
The movies are awesome 		  The new movie is so great 		 Score: 0.6571
